import { Mentor, Booking, User } from '../types';

export const INITIAL_MENTORS: Mentor[] = [
  {
    id: 'm1',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@mentorlink.ai',
    role: 'mentor',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    title: 'Staff AI Research Scientist',
    company: 'Google DeepMind',
    skills: ['Python', 'PyTorch', 'Large Language Models', 'System Design', 'AI Ethics'],
    bio: 'Passionate about guiding the next generation of AI engineers and researchers. 10+ years scaling ML models and mentoring tech leaders.',
    rating: 4.9,
    reviewCount: 48,
    price: 85,
    totalMentees: 124,
    completedSessions: 210,
    experienceYears: 11,
    location: 'San Francisco, CA',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    availability: ['Mon 10:00 AM', 'Tue 02:00 PM', 'Thu 04:00 PM', 'Fri 11:00 AM', 'Sat 01:00 PM'],
    education: ['Ph.D. in Computer Science - Stanford University', 'B.S. in Math & CS - UC Berkeley'],
    experience: [
      {
        role: 'Staff AI Scientist',
        company: 'Google DeepMind',
        duration: '2021 - Present',
        description: 'Leading LLM architecture research and mentor optimization systems.',
      },
      {
        role: 'Senior Machine Learning Engineer',
        company: 'Meta AI',
        duration: '2017 - 2021',
        description: 'Built large-scale recommendation systems and supervised research interns.',
      },
    ],
    reviews: [
      {
        id: 'r1',
        studentName: 'Alex Rivera',
        studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        date: '2 days ago',
        comment: 'Dr. Sarah helped me break down complex LLM attention mechanisms and prepared me for my System Design interview!',
      },
      {
        id: 'r2',
        studentName: 'Marcus Vance',
        studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        date: '1 week ago',
        comment: 'Incredible session. Her actionable advice directly led to my offer at a top AI startup.',
      },
    ],
  },
  {
    id: 'm2',
    name: 'David Miller',
    email: 'david.m@mentorlink.ai',
    role: 'mentor',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    title: 'Principal Frontend Engineer',
    company: 'Stripe',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Web Performance', 'Micro-frontends'],
    bio: 'Crafting pixel-perfect web interfaces for over a decade. I mentor frontend devs on modern React architecture, UI performance, and career growth.',
    rating: 4.95,
    reviewCount: 62,
    price: 75,
    totalMentees: 156,
    completedSessions: 310,
    experienceYears: 9,
    location: 'New York, NY',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    availability: ['Mon 01:00 PM', 'Wed 10:00 AM', 'Thu 03:00 PM', 'Sat 10:00 AM'],
    education: ['B.S. in Software Engineering - MIT'],
    experience: [
      {
        role: 'Principal Frontend Engineer',
        company: 'Stripe',
        duration: '2020 - Present',
        description: 'Architecting core dashboard UI components and design systems.',
      },
      {
        role: 'Senior UI Engineer',
        company: 'Airbnb',
        duration: '2016 - 2020',
        description: 'Developed high-performance booking flows and accessible design tokens.',
      },
    ],
    reviews: [
      {
        id: 'r3',
        studentName: 'Emily Zhang',
        studentAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        date: '3 days ago',
        comment: 'David gave me standard industry code reviews and taught me clean TypeScript patterns. Highly recommend!',
      },
    ],
  },
  {
    id: 'm3',
    name: 'Aisha Patel',
    email: 'aisha.p@mentorlink.ai',
    role: 'mentor',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    title: 'Lead Product Manager',
    company: 'Apple',
    skills: ['Product Strategy', 'UX Design', 'User Research', 'Agile Leadership', 'Product Analytics'],
    bio: 'Guiding ambitious PMs and founders on building user-obsessed products. Specializing in hardware-software integration and mobile apps.',
    rating: 4.88,
    reviewCount: 39,
    price: 90,
    totalMentees: 88,
    completedSessions: 145,
    experienceYears: 8,
    location: 'Cupertino, CA',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    availability: ['Tue 09:00 AM', 'Wed 02:00 PM', 'Fri 04:00 PM'],
    education: ['MBA - Harvard Business School', 'B.A. in Cognitive Science - Northwestern'],
    experience: [
      {
        role: 'Lead Product Manager',
        company: 'Apple',
        duration: '2019 - Present',
        description: 'Managing iOS product experiences and spatial computing apps.',
      },
    ],
    reviews: [
      {
        id: 'r4',
        studentName: 'Julian Thorne',
        studentAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        date: '5 days ago',
        comment: 'Aisha helped me structure my product case study presentation. Passed all rounds!',
      },
    ],
  },
  {
    id: 'm4',
    name: 'Marcus Vance',
    email: 'marcus.v@mentorlink.ai',
    role: 'mentor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    title: 'Senior DevOps & Cloud Architect',
    company: 'Amazon Web Services',
    skills: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD', 'Distributed Systems'],
    bio: 'Helping engineers master cloud infrastructure, container orchestration, and DevOps best practices.',
    rating: 4.92,
    reviewCount: 51,
    price: 80,
    totalMentees: 110,
    completedSessions: 195,
    experienceYears: 10,
    location: 'Seattle, WA',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    availability: ['Mon 04:00 PM', 'Wed 05:00 PM', 'Sat 11:00 AM'],
    education: ['B.S. in Computer Engineering - University of Washington'],
    experience: [
      {
        role: 'Senior Cloud Architect',
        company: 'AWS',
        duration: '2018 - Present',
        description: 'Designing high-availability multi-region Kubernetes clusters.',
      },
    ],
    reviews: [
      {
        id: 'r5',
        studentName: 'Priya Sharma',
        studentAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        date: '1 week ago',
        comment: 'Marcus walked me through AWS VPC architecture line-by-line. Invaluable session!',
      },
    ],
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b101',
    studentId: 's1',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mentorId: 'm1',
    mentorName: 'Dr. Sarah Chen',
    mentorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Staff AI Research Scientist',
    mentorCompany: 'Google DeepMind',
    date: '2026-08-01',
    timeSlot: '10:00 AM',
    topic: 'System Design for AI Applications & LLM Fine-tuning',
    notes: 'Focus on distributed inference optimization and latency reduction strategies.',
    status: 'confirmed',
    createdAt: '2026-07-20T14:30:00Z',
    price: 85,
    meetingLink: 'https://meet.jit.si/MentorLink-Session-b101',
  },
  {
    id: 'b102',
    studentId: 's1',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mentorId: 'm2',
    mentorName: 'David Miller',
    mentorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Principal Frontend Engineer',
    mentorCompany: 'Stripe',
    date: '2026-08-05',
    timeSlot: '02:00 PM',
    topic: 'React Performance Optimization & State Architecture',
    notes: 'Reviewing modern memoization patterns and custom hooks scalability.',
    status: 'pending',
    createdAt: '2026-07-22T09:15:00Z',
    price: 75,
    meetingLink: 'https://meet.jit.si/MentorLink-Session-b102',
  },
  {
    id: 'b103',
    studentId: 's1',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mentorId: 'm3',
    mentorName: 'Aisha Patel',
    mentorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Lead Product Manager',
    mentorCompany: 'Apple',
    date: '2026-07-15',
    timeSlot: '11:00 AM',
    topic: 'Transitioning from Engineering to Product Management',
    notes: 'Discussion on portfolio presentation and strategic metrics.',
    status: 'completed',
    createdAt: '2026-07-10T11:00:00Z',
    price: 90,
    meetingLink: 'https://meet.jit.si/MentorLink-Session-b103',
  },
];

export const DEMO_USERS: Record<string, User> = {
  student: {
    id: 's1',
    name: 'Alex Rivera',
    email: 'alex@student.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Computer Science Graduate Student passionate about AI & Full-Stack Development. Aiming for Senior Engineer roles.',
    title: 'M.S. Computer Science Candidate',
    company: 'UC Berkeley',
    skills: ['React', 'TypeScript', 'Python', 'Machine Learning', 'System Design'],
    location: 'Berkeley, CA',
    github: 'https://github.com/alexrivera',
    linkedin: 'https://linkedin.com/in/alexrivera',
    completedSessions: 8,
  },
  mentor: {
    id: 'm1',
    name: 'Dr. Sarah Chen',
    email: 'sarah@mentor.com',
    role: 'mentor',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    title: 'Staff AI Research Scientist',
    company: 'Google DeepMind',
    skills: ['Python', 'PyTorch', 'Large Language Models', 'System Design', 'AI Ethics'],
    bio: 'Passionate about guiding the next generation of AI engineers and researchers.',
    rating: 4.9,
    reviewCount: 48,
    price: 85,
    totalMentees: 124,
    completedSessions: 210,
    experienceYears: 11,
    location: 'San Francisco, CA',
    github: 'https://github.com/drsarahchen',
    linkedin: 'https://linkedin.com/in/drsarahchen',
  },
};
